apiVersion appsv1
kind Deployment
metadata
  name http-echo
spec
  replicas 2
  selector
    matchLabels
      app http-echo
  template
    metadata
      labels
        app http-echo
    spec
      containers
      - name http-echo
        image ghcr.ioORGhttp-echoIMAGE_TAG
        args
          - -text=Hello from GitOps
        ports
        - containerPort 5678
